language: python
matrix:
    fast_finish: true
    include:
    - python: 3.6
      env:
        - JOB="3.6 No OPENJPEG" ENV_FILE="ci/travis-36-no-opj.yaml"
    - python: 3.6
      env:
        - JOB="3.6" ENV_FILE="ci/travis-36.yaml"
    - python: 3.7
      env:
        - JOB="3.7" ENV_FILE="ci/travis-37.yaml"
    - python: 3.7
      env:
        - JOB="3.7" ENV_FILE="ci/travis-37-no-gdal.yaml"
    - python: 3.8
      env:
        - JOB="3.8" ENV_FILE="ci/travis-38.yaml"
    - python: 3.8
      arch: ppc64le
      env:
        - JOB="3.8" ENV_FILE="ci/travis-38-libgcc-ng9.1.0.yaml"
before_install:
  - echo "before_install"
  - sudo apt-get update
  - df -h
  - pwd
  - uname -a
  - git --version
  - hash -r
  - |
      if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
        sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels
      fi

install:
  - echo "install"
  - ci/setup_env.sh
  - echo "install done"

script:
  - echo "run script"
  - ci/run_script.sh
  - echo "script done"
